# Generated by Django 5.1 on 2024-08-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proimage',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
